
function toggleTheme(){document.body.classList.toggle('dark');localStorage.setItem('theme',document.body.classList.contains('dark')?'dark':'light')}
if(localStorage.getItem('theme')==='dark'){document.body.classList.add('dark')}
let keywords=[];let articles=[];
async function loadData(){
 try{keywords=await fetch('data/content_keywords.json').then(r=>r.json());articles=await fetch('data/articles.json').then(r=>r.json())}catch(e){
 keywords=[{id:1,keyword:'seo friendly content writing',intent:'Informational',cluster:'SEO Writing',volume:2200,allintitle:410,kgr:.19,priority:'High',placement:'H1, intro, H2, meta'}];
 articles=[];
 }
 renderFilters();renderKeywords();renderArticles();analyzeContent();
}
function renderFilters(){const clusters=[...new Set(keywords.map(k=>k.cluster))].sort();const sel=document.getElementById('clusterFilter');clusters.forEach(c=>{const o=document.createElement('option');o.textContent=c;sel.appendChild(o)});['keywordSearch','intentFilter','clusterFilter','priorityFilter'].forEach(id=>document.getElementById(id).addEventListener('input',renderKeywords));}
function renderKeywords(){const q=document.getElementById('keywordSearch').value.toLowerCase();const intent=document.getElementById('intentFilter').value;const cluster=document.getElementById('clusterFilter').value;const priority=document.getElementById('priorityFilter').value;const body=document.getElementById('keywordBody');body.innerHTML='';keywords.filter(k=>(!q||k.keyword.toLowerCase().includes(q))&&(!intent||k.intent===intent)&&(!cluster||k.cluster===cluster)&&(!priority||k.priority===priority)).slice(0,80).forEach(k=>{body.innerHTML+=`<tr><td>${k.id}</td><td><b>${k.keyword}</b></td><td>${k.intent}</td><td>${k.cluster}</td><td>${k.volume}</td><td>${k.allintitle}</td><td>${k.kgr}</td><td>${k.priority}</td><td>${k.placement}</td></tr>`})}
function renderArticles(){const tabs=document.getElementById('articleTabs');const panels=document.getElementById('articlePanels');tabs.innerHTML='';panels.innerHTML='';articles.forEach((a,i)=>{const t=document.createElement('button');t.className='tab'+(i===0?' active':'');t.textContent='Article '+(i+1);t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.articlePanel').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.getElementById('article'+i).classList.add('active')};tabs.appendChild(t);const div=document.createElement('div');div.id='article'+i;div.className='articlePanel card '+(i===0?'active':'');div.innerHTML=`<h3>${a.title}</h3><p><b>Primary Keyword:</b> ${a.primary} • <b>URL Slug:</b> /blog/${a.slug} • <b>SEO Score:</b> ${a.score}/100 • <b>Density:</b> ${a.density}</p><div class="preview"><b>${a.metaTitle}</b><div class="url">www.skillforge.com/blog/${a.slug}</div><div class="desc">${a.metaDescription}</div></div><h4>Heading Outline</h4><ul>${a.outline.map(x=>`<li>${x}</li>`).join('')}</ul><p>This asset demonstrates natural keyword placement, clear information architecture, and conversion-focused writing. It is structured for users who scan quickly and for search engines that analyze topical relevance.</p>`;panels.appendChild(div)})}
function analyzeContent(){const kw=document.getElementById('targetKeyword').value.trim().toLowerCase();const txt=document.getElementById('draftText').value;const clean=txt.toLowerCase();const words=(txt.match(/\b\w+\b/g)||[]).length;const uses=kw?((clean.match(new RegExp(kw.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'g'))||[]).length):0;const density=words?((uses*kw.split(/\s+/).length/words)*100):0;const headings=(txt.match(/^#{1,3}\s/gm)||[]).length;let score=60;if(words>50)score+=10;if(density>=0.5&&density<=2.5)score+=15;if(headings>0)score+=8;if(txt.length>250)score+=7;score=Math.min(score,100);document.getElementById('seoScore').textContent=score;document.getElementById('analysisOutput').textContent=`Word Count: ${words} | Keyword Uses: ${uses} | Density: ${density.toFixed(2)}% | Markdown Headings: ${headings}`}
loadData();
